### ISSUE TITLE
Draw EllipticalArc  

### ISSUE THREAD

**Issue by so-suzuki-kke** [ChrisNikkel/SharpVG#28]
Hello, Chris.

I want to draw EllipticalArc, but I could not build tag like '<path d="M 20,0 a 20 40 0 1 1 0 40">'.
Path.addRelative requires only Point, I could not understand how to add the rest parameters.
Would you teach me the solution?

This library is very nice to me.
Thank you very much.

**Comment by ChrisNikkel** [comment]
Yea, this does look like a bug based on what I see documented here: https://www.w3.org/TR/SVG/paths.html#PathDataEllipticalArcCommands

**Comment by ChrisNikkel** [comment]
Ok, I think I've fixed this and you can see an example here: 
 https://github.com/ChrisNikkel/SharpVG/blob/master/Tests/TestPath.fs#L54
