### ISSUE TITLE
Cannot convert empty body to style in version 0.0.9

### ISSUE THREAD

**Issue by KySpace** [ChrisNikkel/SharpVG#35]
![image](https://user-images.githubusercontent.com/23047275/79056813-23d63b80-7c28-11ea-9da7-048064642dca.png)

The toStyles method throws an error, which prevent any empty groups converting to string.

![image](https://user-images.githubusercontent.com/23047275/79056851-95ae8500-7c28-11ea-893b-7ced71ef7b3e.png)

This is strange since in the code I can see the empty situation is checked.

```
let toStyles body =
        if Seq.isEmpty body then
            Seq.empty
        else
            body
            |> Seq.map (fun b ->
                match b with
                    | Group(g) -> g |> Group.toStyleSet
                    | Element(e) -> e.Style |> Option.toList |> Set.ofList)
            |> Seq.reduce (+)
            |> Set.toSeq
```
I wonder if the published version is the same

**Comment by ChrisNikkel** [comment]
Ah you are right as I hadn't published this bug fix I submitted recently.  New version should be available soon.

**Comment by KySpace** [comment]
I tried with 0.0.10. It is not in there yet. Keep on the good work! I like this repo!

**Comment by ChrisNikkel** [comment]
Are you sure you did a `donnet clean` before building/testing?  I just went to the same folder I used to package the nuget and added the test (see https://github.com/ChrisNikkel/SharpVG/commit/87578cc7c6e84f96149ec55d07939acbfc2ec305) and it passed without any additional changes.  If it is still not working for you I can try to publish another one, but I don't know why that would help at this point.

**Comment by KySpace** [comment]
Yeah I tried multiple methods rebuilding and running the test. The exception is the same. I cloned the repo and ran your test as well and it passed. I guess it is a nuget package issue, would you try testing again with the nuget version rather than reference within the project?

**Comment by ChrisNikkel** [comment]
![image](https://user-images.githubusercontent.com/1404474/79642949-36cf9b00-8155-11ea-8d25-2823fb98c564.png)
Yes, you were right and I think I've fixed it now.

**Comment by KySpace** [comment]
Yes, I believe this is resolved. But I think there is an empty sequence exception thrown here:

```
let rec toStyleSet group =
        group.Body
            |> Seq.map (function | Element(e) -> e.Style |> Option.toList |> Set.ofList | Group(g) -> g |> toStyleSet)
            |> Seq.reduce (+)
```

Now it is true that it seems that `toStyleSet` is only called by `toStyles` and that the empty cases are checked, but that will miss the case where an empty group is nested inside a non-empty group, which will cause the exception since `toStyleSet` is an recursion function. I would suggest to add the empty check in `toStyleSet` as well, or just for the peace of the mind, use `fold` to replace all `reduce` functions (Although I do believe these are the only two).

I hope this will prevent all the exceptions. Thanks for the effort!

**Comment by ChrisNikkel** [comment]
Good point, thanks!

**Comment by KySpace** [comment]
It works! Thank you!
