### ISSUE TITLE
Bounce example missing

### ISSUE THREAD

**Issue by misterspeedy** [ChrisNikkel/SharpVG#41]
In the doc here: https://chrisnikkel.github.io/SharpVG/

We have

```
cd Examples\Bounce\src
dotnet restore
dotnet fable yarn-run start
```

But the `Bounce` directory doesn't exist.

**Comment by ChrisNikkel** [comment]
Thanks.  This example kept breaking since Fable went through some significant changes recently.  The concept should still work and I'd be happy to help you get it work if needed.
