### ISSUE TITLE
Notebooks using HtmlString

### ISSUE THREAD

**Issue by grenaad** [ChrisNikkel/SharpVG#45]
**HtmlString** should be **HTML** in the notebook examples

https://github.com/ChrisNikkel/SharpVG/blob/9ecbd5f25b47ad5ddcca3b0bc5d8082b9856a71b/Examples/Notebooks/SharpVG.dib#L14

I did not test with a Jupyter notebook, but I assume it will be same issue.
https://github.com/ChrisNikkel/SharpVG/blob/9ecbd5f25b47ad5ddcca3b0bc5d8082b9856a71b/Examples/Notebooks/SharpVG.ipynb#L23

It seems that `HtmlString` was been imported with `Microsoft.DotNet.Interactive.FSharp.FSharpKernelHelpers;`, but it is no longer the case with .NET 5

Tested with:
.NET SDK: 5.0.101
.NET Interactive Notebooks: v1.0.160901

**Comment by ChrisNikkel** [comment]
Thanks for calling this out!
