### ISSUE TITLE
Usage with Fable?

### ISSUE THREAD

**Issue by EHotwagner** [ChrisNikkel/SharpVG#49]
Is there an example how to use this library with fable?
Is it usable from fable?
Probably more a fable question but how do you cast/convert your svgs to fable usable types?

**Comment by ChrisNikkel** [comment]
I used to have an example, but after Fable upgraded I didn't keep it up to date so I removed it.  Its likely the same technique today as what I did before: https://github.com/ChrisNikkel/SharpVG/blob/f18637c25330febfcbd071dcb9738c66a47e8acd/Examples/Bounce/src/App.fs#L60

**Comment by EHotwagner** [comment]
Thanks a lot. Yes, that seems very likely to work. A different candidate might be https://betterprogramming.pub/what-is-dangerouslysetinnerhtml-6d6a98cbc187 when using a react wrapper. I will report back and close when i got time to test it a bit.

**Comment by EHotwagner** [comment]
Works fine. With Feliz i used props.dangerouslysetinnerhtml .
